data = [
  ["Context_Sentence","HerAlsoStop","Test_Sentence","context_sound_filename","test_sound_filename","Count - Test_Sentence"  ],
  ["This week, these kids went to Falls Creek for the first time. At the beginning of the week, some kids went to the Falls Creek aquarium, and some went to the Falls Creek bakery.","Again","Exactly one kid went to the Falls Creek bakery again on Wednesday.","kids_aquariumbakery.wav","kid_Again_bakery_FallsCreek.wav","9"  ],
  ["","Also","Exactly one kid also went to the Falls Creek bakery on Wednesday.","kids_aquariumbakery.wav","kid_Also_bakery_FallsCreek.wav","9"  ],
  ["","GoBack","Exactly one kid went back to the Falls Creek bakery on Wednesday.","kids_aquariumbakery.wav","kid_GoBack_bakery_FallsCreek.wav","9"  ],
  ["","Return","Exactly one kid returned to the Falls Creek bakery on Wednesday.","kids_aquariumbakery.wav","kid_Return_bakery_FallsCreek.wav","9"  ],
  ["","Stop","Exactly one kid stopped going to the Falls Creek bakery on Wednesday.","kids_aquariumbakery.wav","kid_Stop_bakery_FallsCreek.wav","9"  ],
  ["This week, these kids went to Fernville for the first time. At the beginning of the week, some kids went to the Fernville pool, and some went to the Fernville party store.","Again","Exactly one kid went to the Fernville party store again on Wednesday.","kids_poolparty.wav","kid_Again_party_Fernville.wav","9"  ],
  ["","Also","Exactly one kid also went to the Fernville party store on Wednesday.","kids_poolparty.wav","kid_Also_party_Fernville.wav","9"  ],
  ["","GoBack","Exactly one kid went back to the Fernville party store on Wednesday.","kids_poolparty.wav","kid_GoBack_party_Fernville.wav","9"  ],
  ["","Return","Exactly one kid returned to the Fernville party store on Wednesday.","kids_poolparty.wav","kid_Return_party_Fernville.wav","9"  ],
  ["","Stop","Exactly one kid stopped going to the Fernville party store on Wednesday.","kids_poolparty.wav","kid_Stop_party_Fernville.wav","9"  ],
  ["This week, these kids went to Jackson for the first time. At the beginning of the week, some kids went to the Jackson aquarium, and some went to the Jackson themepark.","Again","Exactly one kid went to the Jackson themepark again on Wednesday.","kids_aquariumthemepark.wav","kid_Again_themepark_Jackson.wav","9"  ],
  ["","Also","Exactly one kid also went to the Jackson themepark on Wednesday.","kids_aquariumthemepark.wav","kid_Also_themepark_Jackson.wav","9"  ],
  ["","GoBack","Exactly one kid went back to the Jackson themepark on Wednesday.","kids_aquariumthemepark.wav","kid_GoBack_themepark_Jackson.wav","9"  ],
  ["","Return","Exactly one kid returned to the Jackson themepark on Wednesday.","kids_aquariumthemepark.wav","kid_Return_themepark_Jackson.wav","9"  ],
  ["","Stop","Exactly one kid stopped going to the Jackson themepark on Wednesday.","kids_aquariumthemepark.wav","kid_Stop_themepark_Jackson.wav","12"  ],
  ["This week, these kids went to Milford for the first time. At the beginning of the week, some kids went to the Milford computer lab, and some went to the Milford beach.","Again","Exactly one kid went to the Milford computer lab again on Wednesday.","kids_computerbeach.wav","kid_Again_computer_Milford.wav","9"  ],
  ["","Also","Exactly one kid also went to the Milford computer lab on Wednesday.","kids_computerbeach.wav","kid_Also_computer_Milford.wav","9"  ],
  ["","GoBack","Exactly one kid went back to the Milford computer lab on Wednesday.","kids_computerbeach.wav","kid_GoBack_computer_Milford.wav","9"  ],
  ["","Return","Exactly one kid returned to the Milford computer lab on Wednesday.","kids_computerbeach.wav","kid_Return_computer_Milford.wav","9"  ],
  ["","Stop","Exactly one kid stopped going to the Milford computer lab on Wednesday.","kids_computerbeach.wav","kid_Stop_computer_Milford.wav","9"  ],
  ["This week, these kids went to Ore City for the first time. At the beginning of the week, some kids went to the Ore City salon, and some went to the Ore City supermarket.","Again","Exactly one kid went to the Ore City salon again on Wednesday.","kids_salonsupermarket.wav","kid_Again_salon_OreCity.wav","9"  ],
  ["","Also","Exactly one kid also went to the Ore City salon on Wednesday.","kids_salonsupermarket.wav","kid_Also_salon_OreCity.wav","9"  ],
  ["","GoBack","Exactly one kid went back to the Ore City salon on Wednesday.","kids_salonsupermarket.wav","kid_GoBack_salon_OreCity.wav","9"  ],
  ["","Return","Exactly one kid returned to the Ore City salon on Wednesday.","kids_salonsupermarket.wav","kid_Return_salon_OreCity.wav","9"  ],
  ["","Stop","Exactly one kid stopped going to the Ore City salon on Wednesday.","kids_salonsupermarket.wav","kid_Stop_salon_OreCity.wav","9"  ],
  ["This week, these kids went to West Bay Shore for the first time. At the beginning of the week, some kids went to the West Bay Shore movie theater, and some went to the West Bay Shore orchard.","Again","Exactly one kid went to the West Bay Shore movie theater again on Wednesday.","kids_moviesorchard.wav","kid_Again_movies_WestBayShore.wav","9"  ],
  ["","Also","Exactly one kid also went to the West Bay Shore movie theater on Wednesday.","kids_moviesorchard.wav","kid_Also_movies_WestBayShore.wav","9"  ],
  ["","GoBack","Exactly one kid went back to the West Bay Shore movie theater on Wednesday.","kids_moviesorchard.wav","kid_GoBack_movies_WestBayShore.wav","9"  ],
  ["","Return","Exactly one kid returned to the West Bay Shore movie theater on Wednesday.","kids_moviesorchard.wav","kid_Return_movies_WestBayShore.wav","9"  ],
  ["","Stop","Exactly one kid stopped going to the West Bay Shore movie theater on Wednesday.","kids_moviesorchard.wav","kid_Stop_movies_WestBayShore.wav","9"  ],
  ["This week, these people went to Dodgeville for the first time. At the beginning of the week, some people went to the Dodgeville library, and some went to the Dodgeville movie theater.","Again","Exactly one person went to the Dodgeville movie theater again on Wednesday.","people_librarymovies.wav","person_Again_movies_Dodgeville.wav","9"  ],
  ["","Also","Exactly one person also went to the Dodgeville movie theater on Wednesday.","people_librarymovies.wav","person_Also_movies_Dodgeville.wav","9"  ],
  ["","GoBack","Exactly one person went back to the Dodgeville movie theater on Wednesday.","people_librarymovies.wav","person_GoBack_movies_Dodgeville.wav","9"  ],
  ["","Return","Exactly one person returned to the Dodgeville movie theater on Wednesday.","people_librarymovies.wav","person_Return_movies_Dodgeville.wav","9"  ],
  ["","Stop","Exactly one person stopped going to the Dodgeville movie theater on Wednesday.","people_librarymovies.wav","person_Stop_movies_Dodgeville.wav","9"  ],
  ["This week, these people went to Franktown for the first time. At the beginning of the week, some people went to the Franktown pool, and some went to the Franktown salon.","Again","Exactly one person went to the Franktown salon again on Wednesday.","people_poolsalon.wav","person_Again_salon_Franktown.wav","9"  ],
  ["","Also","Exactly one person also went to the Franktown salon on Wednesday.","people_poolsalon.wav","person_Also_salon_Franktown.wav","9"  ],
  ["","GoBack","Exactly one person went back to the Franktown salon on Wednesday.","people_poolsalon.wav","person_GoBack_salon_Franktown.wav","9"  ],
  ["","Return","Exactly one person returned to the Franktown salon on Wednesday.","people_poolsalon.wav","person_Return_salon_Franktown.wav","9"  ],
  ["","Stop","Exactly one person stopped going to the Franktown salon on Wednesday.","people_poolsalon.wav","person_Stop_salon_Franktown.wav","9"  ],
  ["This week, these people went to Lexington for the first time. At the beginning of the week, some people went to the Lexington library, and some went to the Lexington computer lab.","Again","Exactly one person went to the Lexington computer lab again on Wednesday.","people_librarycomputer.wav","person_Again_computer_Lexington.wav","9"  ],
  ["","Also","Exactly one person also went to the Lexington computer lab on Wednesday.","people_librarycomputer.wav","person_Also_computer_Lexington.wav","9"  ],
  ["","GoBack","Exactly one person went back to the Lexington computer lab on Wednesday.","people_librarycomputer.wav","person_GoBack_computer_Lexington.wav","9"  ],
  ["","Return","Exactly one person returned to the Lexington computer lab on Wednesday.","people_librarycomputer.wav","person_Return_computer_Lexington.wav","9"  ],
  ["","Stop","Exactly one person stopped going to the Lexington computer lab on Wednesday.","people_librarycomputer.wav","person_Stop_computer_Lexington.wav","9"  ],
  ["This week, these people went to Lynnwood for the first time. At the beginning of the week, some people went to the Lynnwood bakery, and some went to the Lynnwood beach.","Again","Exactly one person went to the Lynnwood bakery again on Wednesday.","people_bakerybeach.wav","person_Again_bakery_Lynnwood.wav","9"  ],
  ["","Also","Exactly one person also went to the Lynnwood bakery on Wednesday.","people_bakerybeach.wav","person_Also_bakery_Lynnwood.wav","9"  ],
  ["","GoBack","Exactly one person went back to the Lynnwood bakery on Wednesday.","people_bakerybeach.wav","person_GoBack_bakery_Lynnwood.wav","9"  ],
  ["","Return","Exactly one person returned to the Lynnwood bakery on Wednesday.","people_bakerybeach.wav","person_Return_bakery_Lynnwood.wav","9"  ],
  ["","Stop","Exactly one person stopped going to the Lynnwood bakery on Wednesday.","people_bakerybeach.wav","person_Stop_bakery_Lynnwood.wav","9"  ],
  ["This week, these people went to Montello for the first time. At the beginning of the week, some people went to the Montello themepark, and some went to the Montello supermarket.","Again","Exactly one person went to the Montello themepark again on Wednesday.","people_themeparksupermarket.wav","person_Again_themepark_Montello.wav","9"  ],
  ["","Also","Exactly one person also went to the Montello themepark on Wednesday.","people_themeparksupermarket.wav","person_Also_themepark_Montello.wav","9"  ],
  ["","GoBack","Exactly one person went back to the Montello themepark on Wednesday.","people_themeparksupermarket.wav","person_GoBack_themepark_Montello.wav","8"  ],
  ["","Return","Exactly one person returned to the Montello themepark on Wednesday.","people_themeparksupermarket.wav","person_Return_themepark_Montello.wav","9"  ],
  ["","Stop","Exactly one person stopped going to the Montello themepark on Wednesday.","people_themeparksupermarket.wav","person_Stop_themepark_Montello.wav","9"  ],
  ["This week, these people went to Thousand Palms for the first time. At the beginning of the week, some people went to the Thousand Palms party store, and some went to the Thousand Palms orchard.","Again","Exactly one person went to the Thousand Palms party store again on Wednesday.","people_partyorchard.wav","person_Again_party_ThousandPalms.wav","9"  ],
  ["","Also","Exactly one person also went to the Thousand Palms party store on Wednesday.","people_partyorchard.wav","person_Also_party_ThousandPalms.wav","9"  ],
  ["","GoBack","Exactly one person went back to the Thousand Palms party store on Wednesday.","people_partyorchard.wav","person_GoBack_party_ThousandPalms.wav","9"  ],
  ["","Return","Exactly one person returned to the Thousand Palms party store on Wednesday.","people_partyorchard.wav","person_Return_party_ThousandPalms.wav","9"  ],
  ["","Stop","Exactly one person stopped going to the Thousand Palms party store on Wednesday.","people_partyorchard.wav","person_Stop_party_ThousandPalms.wav","9"  ],
  ["Total Result","","","","","542"  ]
];